[tool.black]
line-length = 100

[tool.ruff]
# Same as Black.
line-length = 100
# Enable Pyflakes `E` and `F` codes by default.
# Enable flake8-bugbear `B` codes by default.
# Enable isort `I` codes by default.
# Enable flake8-quotes `Q` codes by default.
# Enable flake8-comprehensions `C4` codes by default.
# Enable pyupgrade `UP` codes by default.
select = ["E", "F", "W", "I", "B", "Q", "C4", "UP"]
ignore = []

# Allow unused variables when underscore-prefixed.
# ignore = ["F841"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "sensitivity_results", # Exclude generated results
    "figs", # Exclude generated figures
    "papers", # Exclude paper files
    "measurement_analysis", # Exclude data analysis dirs
    "perturbation_analysis/plots", # Exclude generated plots
]

# Assume Python 3.8+
target-version = "py38"

[tool.ruff.lint]
# Allow unused variables in `__init__.py` files.
ignore = ["F401"] # Ignore unused imports for now, can tighten later

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"